/*
 * app.c
 *
 *  Created on: Oct 13, 2022
 *      Author: khaled
 */
#include "app.h"


void NORMAL_mode(void){
	//CAR GREEN LED ON FOR 5 SECONDS
	LED_on(CAR_TRAFFIC_PORT, CAR_GREEN_LED);
	LED_on(PEDESTRIAN_TRAFFIC_PORT, PEDESTRIAN_RED_LED);
	TIMER0_delay(5);
	//CAR GREEN LED OFF AND CAR YELLOW LED BLINKS FOR 5 SECONDS
	LED_off(CAR_TRAFFIC_PORT, CAR_GREEN_LED);
	LED_off(PEDESTRIAN_TRAFFIC_PORT, PEDESTRIAN_RED_LED);
	for(int i = 0; i < 5; i++){
		LED_toggle(CAR_TRAFFIC_PORT, CAR_YELLOW_LED);
		LED_toggle(PEDESTRIAN_TRAFFIC_PORT, PEDESTRIAN_YELLOW_LED);
		TIMER0_delay(1);
	}
	//CAR YELLOW LED OFF AND CAR RED LED ON FOR 5 SECONDS
	LED_off(CAR_TRAFFIC_PORT, CAR_YELLOW_LED);
	LED_off(PEDESTRIAN_TRAFFIC_PORT, PEDESTRIAN_YELLOW_LED);
	LED_on(CAR_TRAFFIC_PORT, CAR_RED_LED);
	LED_on(PEDESTRIAN_TRAFFIC_PORT, PEDESTRIAN_GREEN_LED);
	TIMER0_delay(5);
	//CAR RED LED OFF AND CAR YELLOW LED BLINKS FOR 5 SECONDS
	LED_off(CAR_TRAFFIC_PORT, CAR_RED_LED);
	LED_off(PEDESTRIAN_TRAFFIC_PORT, PEDESTRIAN_GREEN_LED);
	for(int i = 0; i < 5; i++){
		LED_toggle(CAR_TRAFFIC_PORT, CAR_YELLOW_LED);
		LED_toggle(PEDESTRIAN_TRAFFIC_PORT, PEDESTRIAN_YELLOW_LED);
		TIMER0_delay(1);
	}
	LED_off(CAR_TRAFFIC_PORT, CAR_YELLOW_LED);
	LED_off(PEDESTRIAN_TRAFFIC_PORT, PEDESTRIAN_YELLOW_LED);
}

void PEDESTRIAN_mode(void){
	uint8_t CAR_GREEN, CAR_YELLOW, CAR_RED;
	LED_state(CAR_TRAFFIC_PORT, CAR_GREEN_LED, &CAR_GREEN);
	LED_state(CAR_TRAFFIC_PORT, CAR_YELLOW_LED, &CAR_YELLOW);
	LED_state(CAR_TRAFFIC_PORT, CAR_RED_LED, &CAR_RED);
	//IF PRESSED WHEN CAR RED LED IS ON
	if(CAR_RED==ON){
		//PEDESTRIAN GREEN LED ON FOR 5 SECONDS
		LED_on(PEDESTRIAN_TRAFFIC_PORT, PEDESTRIAN_GREEN_LED);
		LED_on(CAR_TRAFFIC_PORT, CAR_RED_LED);
		TIMER0_delay(5);
	}
	//IF PRESSED WHEN CAR GREEN LED OR YELLOW LED IS ON
	else if(CAR_GREEN==ON || CAR_YELLOW==ON){
		//PEDSTRIAN RED LED ON AND BOTH YELLOW LEDS BLINK FOR 5 SECONDS
		LED_on(PEDESTRIAN_TRAFFIC_PORT, PEDESTRIAN_RED_LED);
		for(int i = 0; i < 5; i++){
			LED_toggle(CAR_TRAFFIC_PORT, CAR_YELLOW_LED);
			LED_toggle(PEDESTRIAN_TRAFFIC_PORT, PEDESTRIAN_YELLOW_LED);
			TIMER0_delay(1);
		}
		LED_off(CAR_TRAFFIC_PORT, CAR_YELLOW_LED);
		LED_off(PEDESTRIAN_TRAFFIC_PORT, PEDESTRIAN_YELLOW_LED);
		LED_off(CAR_TRAFFIC_PORT, CAR_GREEN_LED);
		LED_off(PEDESTRIAN_TRAFFIC_PORT, PEDESTRIAN_RED_LED);
		//CAR RED LED ON AND PEDSTRIAN GREEN LED ON FOR 5 SECONDS
		LED_on(CAR_TRAFFIC_PORT, CAR_RED_LED);
		LED_on(PEDESTRIAN_TRAFFIC_PORT, PEDESTRIAN_GREEN_LED);
		TIMER0_delay(5);
	}
	//AT THE END OF THE TWO STATES
	//CAR RED LED IS OFF AND BOTH YELLOW LEDS BLINK FOR 5 SECONDS
	for(int i = 0; i < 5; i++){
		LED_toggle(CAR_TRAFFIC_PORT, CAR_YELLOW_LED);
		LED_toggle(PEDESTRIAN_TRAFFIC_PORT, PEDESTRIAN_YELLOW_LED);
		TIMER0_delay(1);
	}
	LED_off(PEDESTRIAN_TRAFFIC_PORT, PEDESTRIAN_GREEN_LED);
	LED_off(CAR_TRAFFIC_PORT, CAR_RED_LED);
	LED_off(CAR_TRAFFIC_PORT, CAR_YELLOW_LED);
	LED_off(PEDESTRIAN_TRAFFIC_PORT, PEDESTRIAN_YELLOW_LED);
	//AFTER FIVE SECONDS PEDSTRIAN GREEN LED OFF AND BOTH PEDSTRIAN RED LED AND CAR GREEN LED ON
	LED_on(CAR_TRAFFIC_PORT, CAR_GREEN_LED);
	LED_on(PEDESTRIAN_TRAFFIC_PORT, PEDESTRIAN_RED_LED);
	TIMER0_init();
	return APP_start();

}

void APP_init(){
	//INITIALIZING TIMER 0
	TIMER0_init();
	//INITIALIZING EXTERNAL INTERRUPT 0
	EXT_INT_0_init();
	//INITIALIZING CAR TRAFFIC LEDS AS OUTPUTS
	LED_init(CAR_TRAFFIC_PORT, CAR_GREEN_LED);
	LED_init(CAR_TRAFFIC_PORT, CAR_YELLOW_LED);
	LED_init(CAR_TRAFFIC_PORT, CAR_RED_LED);
	//INITIALIZING PEDESTRIAN TRAFFIC LEDS AS OUTPUTS
	LED_init(PEDESTRIAN_TRAFFIC_PORT, PEDESTRIAN_GREEN_LED);
	LED_init(PEDESTRIAN_TRAFFIC_PORT, PEDESTRIAN_YELLOW_LED);
	LED_init(PEDESTRIAN_TRAFFIC_PORT, PEDESTRIAN_RED_LED);
	//INITIALIZING PEDESTRIAN INTERRUPT BUTTON AS INPUT
	BUTTON_init(PEDESTRIAN_BUTTON_PORT, PEDESTRIAN_BUTTON);
}
void APP_start(){
	while(1){
		NORMAL_mode();
	}
}

//ISR FUNCTION STRUCTURE
ISR(EXT_INT_0){
	//DECLARING VARIABLE TO DETECT LONG PRESS
	uint8_t isPressed=0;
	TIMER0_delay(1);
	BUTTON_read(PEDESTRIAN_BUTTON_PORT, PEDESTRIAN_BUTTON, &isPressed);
	if(isPressed==1){
		//IF LONG PRESS IGNORE IT
		TIMER0_init();
		return;
	}
	else{
		//ELSE IT'S SHORT PRESS
		PEDESTRIAN_mode();
	}
}
