/*
 * interrupt.c
 *
 *  Created on: Oct 13, 2022
 *      Author: khaled
 */
#include "interrupt.h"
//FUNCTION TO INITIALIZE EXTERNAL INTERUPT 0
EN_INTERRUPT0_error_t EXT_INT_0_init(void){
	//ENABLING INTERRUPT IN STATUS REGISTER
	SET_BIT(SREG, BIT7);
	//RISING EDGE ON INT0 GENERATES INTERRUPT REQUEST.
	SET_BIT(MCUCR, BIT0);
	SET_BIT(MCUCR, BIT1);
	//ENABLING EXTERNAL INTERRUPT PIN INT0
	SET_BIT(GICR, BIT6);
	return INTERRUPT_OK;
}


